# Training
seed: 42
epochs: 20
trial_num: 5
num_classes: 2
eta_min: 1.0e-6
learning_rate: 1.0e-4
grad_accumulation: 12
feature_extractor: UNI

# Regularization
weight_decay: 1.0e-5
label_smoothing: 0.0
dropout_probability: 0.0

# Model
model: resnet
version:
variant: resnet18