# Training
pad: True
seed: 42
epochs: 20
trial_num: 3
batch_size: 12
num_classes: 2
eta_min: 1.0e-6
learning_rate: 1.0e-4
grad_accumulation: 1
feature_extractor: UNI
target_shape: [350, 224]

# Regularization
weight_decay: 1.0e-3
label_smoothing: 0.2
dropout_probability: 0.0

# Model
model: resnet
version:
variant: resnet18
normalization_method: batch