# Training
seed: 42
epochs: 50
trial_num: 1
model: resnet
num_classes: 2
eta_min: 1.0e-6
learning_rate: 1.0e-4
grad_accumulation: 12
feature_extractor: UNI

# Regularization
weight_decay: 0.0
label_smoothing: 0.0
dropout_probability: 0.0

# Model
variant: resnet18
version: None